version: v1
auth:
  token: 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
branch:
  projects:
    - admin
    - player
  owners:
    admin: surya-apty 
    player: soni
  meta:
    maxLength: 150
    shouldIncludeTicketNo: true
    ticketRegex: /\[\s(CB|LSP)-\d+\s\]/g


  
  
  


  


