version: v1
branch:
  branchType:
    - feature
    - bugfix
    - enhancement
  ticketType:
    - CB
    - LSP
  shouldIncludeTicketNo: true
  ticketIDRegex: /\[\s(CB|LSP)-\d+\s\]/g
  regex: /\[\s(CB|LSP)-\d+\s\]/g


  


