version: v1
branch:
  projects:
    - admin
    - player
  owners:
    admin: surya-apty 
    player: soni
  meta:
    maxLength: 100
  rules:
    branchType:
      name: 'Should define type of branch'
      regex: /^(feature|bugfix|enhancement)\/&/g
    includeTicketNo:
      name: 'Should include ticket no'
      regex: /\[\s(CB|LSP)-\d+\s\]/g

  
  
  


  


