version: v1
branch:
  projects:
    - admin
    - player
  owners:
    admin: surya-apty 
    player: soni
  meta:
    maxLength: 150
    shouldIncludeTicketNo: true
    ticketRegex: /\[\s(CB|LSP)-\d+\s\]/g


  
  
  


  


