version: v1
branch:
  base: feature/LSP-12345/some-feature-branch
  reviewer:
   - surya-apty
   - soni
  projects:
    - admin
    - player
  owners:
    admin: surya-apty 
    player: soni
  meta:
    maxLength: 150
    shouldIncludeTicketNo: true
    ticketRegex: /\[\s(CB|LSP)-\d+\s\]/g


  
  
  

